# Generated by Django 4.2.13 on 2024-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_phonenumber_additional_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('rather_not_say', 'Rather not say')], max_length=15),
        ),
    ]
