# Generated by Django 4.2.13 on 2024-05-27 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_phonenumber_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='additional_phone_number',
        ),
        migrations.CreateModel(
            name='AdditionalPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_number', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_phone_numbers', to='contacts.contact')),
            ],
        ),
    ]
